name: Build MBS OS
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: sudo apt-get update && sudo apt-get install -y gcc binutils make git xorriso mtools
      - name: Clone limine
        run: git clone https://github.com/limine-bootloader/limine.git --branch=v7.x-binary --depth=1
      - name: Copy header
        run: cp limine/limine.h.
      - name: Make limine
        run: make -C limine
      - name: Config
        run: printf "TIMEOUT=0\n:MBS OS\nPROTOCOL=limine\nKERNEL_PATH=boot:///boot/mbs_kernel.elf\n" > limine.cfg
      - name: Compile
        run: gcc -c kernel.c -o kernel.o -ffreestanding -nostdlib -m64 -mcmodel=kernel -fno-pic -fno-pie -fno-stack-protector -mno-red-zone
      - name: Link
        run: ld -T linker.ld kernel.o -o mbs_kernel.elf
      - name: Make iso dir
        run: mkdir -p iso_root/boot/limine && cp mbs_kernel.elf limine.cfg iso_root/boot/ && cp limine/limine-bios.sys limine/limine-bios-cd.bin limine/limine-uefi-cd.bin iso_root/boot/limine/
      - name: Build ISO
        run: xorriso -as mkisofs -b boot/limine/limine-bios-cd.bin -no-emul-boot -boot-load-size 4 -boot-info-table --efi-boot boot/limine/limine-uefi-cd.bin -efi-boot-part --efi-boot-image --protective-msdos-label iso_root -o MBS-OS.iso
      - name: Bios install
        run:./limine/limine bios-install MBS-OS.iso
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: MBS-OS-ISO
          path: MBS-OS.iso
          
